### PR TITLE
update to latest cooler; bump version; docker to be rebuilt

### PR DESCRIPTION
**Pull request by sergpolly**
trying to resolve https://github.com/mirnylab/distiller-nf/issues/136 in distiller
not sure if installing `git+https://github.com/mirnylab/cooler@develop` is the best - but could be a temporary solution , just to rebuild and republish a container-image , no ?

distiller-tests would fail now, as there is no `mirnylab/distiller_nf:0.3.2` in the dockerhub

### CODE REVIEW

**Comment by golobor** [comment]
ugggh, must admit - not a fan of such a temporary solution. Maybe we can instead nudge @nvictus to make a new release, such that I could just recompile a new docker image?

**Comment by sergpolly** [comment]
100% agree
I just wanted to initiate this "discussion", because @nandankita seems to be heavily affected by this bug and I also didn't want to updated just the distiller image on our share cluster - even more temporary, and ugly

So, @nandankita we'd need to wait a bit for the release

**Comment by nandankita** [comment]
Got it! No worries. I should be able to run distiller without the singularity image till then.

**Comment by sergpolly** [comment]
addressed in https://github.com/mirnylab/distiller-nf/commit/f3da06f2ea321ee03500e3b825ccd12ee82d8213

**Pull request closed without merging**
