### PR TITLE
Ghpcc

### PR DESCRIPTION
**Pull request by sergpolly**
I do not mean to PR all of those commits, just to cherry-pick 3 or 4 latest ones.

All for the sake of a "new feature" - sort of:
 - We propose to add a "custom" profile to mainline distiller
 - this would enable users to plugin a custom-config for their specific hardware, like so:
      - `nextflow run mirnylab/distiller-nf -profile custom --custom_config /full/path/to/myhardware.config`
 - the current way of replacing default `local` and `cluster` in the configs folder is a bit inconvenient
     - especially if someone is executing the pipeline like so `nextflow run mirnylab/distiller-nf -profile cluster` - there is no mechanism to substitute whatever is in the `configs` folder in the repo
     - there is a mechanism to substitute default `nextflow.config`, probably - but arguably we don't need that, as we want to keep container path, version and other things - as in defaults, but to customize the hardware-part only
 - maybe eventually we'd get rid of `profile cluster/local`, but for now just merging `custom` seems like easiest

We tried this modification in our fork and tested it using different configs - it works fine .
Also we've switched to this "automated" nextflow pipeline execution : `nextflow run mirnylab/distiller-nf` - which makes `nextflow` to pull latest `distiller-nf` from github (it's stored in `~/.nextflow` by default), run the pipeline and store the results in a different place `./` .

If we agree on this `custom` profile thing, I can try to merge this myself by doing something like this https://mattstauffer.com/blog/how-to-merge-only-specific-commits-from-a-pull-request/

### CODE REVIEW

**Comment by golobor** [comment]
I like this, both the motivation and the simple solution!
Though, why did you replace storeDirs with publishDirs?
Sorry, I have no experience with squashfs :(

**Comment by sergpolly** [comment]
I'm glad you like it!
Initially it was just a branch for our ghpcc cluster - minimal modifications from the mainline distiller to make it usable for us. It breaks a lot with `storeDirs` unfortunately - so I typically replace them with `publishDirs` ... Custom profile came later - so i'm proposing just to cherry pick last 3 commits instead of merging everything

**Comment by sergpolly** [comment]
Just to get custom configs to the mainline distiller , I mean - not the `publishDirs`

I'll try to do the cherry picking thing as long as we agreed about the feature

Squashfs is completely unrelated, sorry about that

**Comment by sergpolly** [comment]
Did it manually with instructions from https://lalatendu.org/2015/12/02/cherry-pick-a-pr-pull-request-from-github/

in nutshell: 
 - go to individual commit's address, e.g. https://github.com/mirnylab/distiller-nf/pull/138/commits/71caaeeab4907a502620a32567be5894c8080e4d
 - suffix it with the .patch -> https://github.com/mirnylab/distiller-nf/pull/138/commits/71caaeeab4907a502620a32567be5894c8080e4d.patch
 - it would redirect to https://github.com/mirnylab/distiller-nf/commit/71caaeeab4907a502620a32567be5894c8080e4d.patch
 - then use this patch with `git am` command: `curl https://github.com/mirnylab/distiller-nf/commit/71caaeeab4907a502620a32567be5894c8080e4d.patch | git am`
 - occasional conflict maybe resolved using, e.g. `https://github.com/mirnylab/distiller-nf/commit/71caaeeab4907a502620a32567be5894c8080e4d.patch | sed "s/'lz4'/'gz'/g" | git am`

it is completely manual and we would need to close PR instead of pulling it, but it seems like there is no easy mechanism to `cherry-pick` individual commits directly from github ...

all set!

**Pull request closed without merging**
